#pragma once
#include <cstdint>
#include <string>
#include <string.h>
#include <fstream>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <vector>
#include <algorithm>
#include <filesystem>